create user BDDzone2 identified by password ;

GRANT CREATE TYPE, CREATE VIEW TO BDDzone2;
GRANT CREATE SESSION TO BDDzone2;
GRANT CREATE TABLE TO BDDzone2;
GRANT UNLIMITED TABLESPACE TO BDDzone2 ;

GRANT CREATE SEQUENCE TO BDDzone2 ;
GRANT CREATE TRIGGER TO BDDzone2;